# Snowflake Connection Configuration
# Replace these values with your actual Snowflake connection details

[connections.snowflake]
account = "your-account-identifier"
user = "your-username"
password = "your-password"
role = "your-role"
warehouse = "your-warehouse"
database = "your-database"
schema = "your-schema"

# Alternative authentication methods:
# For key-pair authentication:
# private_key_file = "path/to/your/private_key.pem"
# private_key_passphrase = "your-passphrase"  # if your private key has a passphrase

# For SSO/External Browser authentication:
# authenticator = "externalbrowser"
